### ISSUE TITLE
Collaboration opportunity with c4spar/deno-dzx

### ISSUE THREAD

**Issue by andrewbrey** [dsherret/ax#1]
First, thank you for your work on Deno! I really enjoy the quality of what you and the team build :smile:  

I would normally have made something like this a `Discussion` topic instead of an issue, but I wonder if you've had thoughts on collaborating on https://github.com/c4spar/deno-dzx to add your ideas to that project? It is the most established Deno version of `zx` that I've seen (and contributed to) and I think it might be valuable to cross-pollinate ideas in that more established project!

Just wanted to put it on your radar in case you haven't already seen it - cheers!

**Comment by dsherret** [comment]
Hey, I've seen it, but I don't really like how zx and dzx use a global command, have a cli, and use the system shell (both of those tools don't work well on Windows) so this is a complete rewrite.

**Comment by andrewbrey** [comment]
@dsherret Ah, makes sense! Thanks again for your work on Deno and the ecosystem, looking forward to seeing what you build here :+1:

**Comment by dsherret** [comment]
Thanks, yeah overall I really like both those projects, but I want a complete rewrite that's slimmed down and only with a shell that works cross platform.

**Comment by sigmaSd** [comment]
Hello, I like the crossplatform shell part and I feel like its an opportunity to make it a base that different competing project can build on . https://github.com/dsherret/ax/blob/main/src/shell.ts seems like a rewrite of the rust part, what about moving this and the whole binding part to deno_task_shell so anyone one can depend on it.

For example deno-dzx would definitely benefit from it, and personally I have my own project that would benefit https://github.com/sigmaSd/ds as well from it.

what do you think @dsherret ?
also cc @c4spar

**Comment by sigmaSd** [comment]
Also currently I can just depend on https://github.com/dsherret/ax/blob/main/src/shell.ts and make it work but my point is moving it to a different project would give a bigger guarantee that it wont be interleaved with ax specific code.

**Comment by dsherret** [comment]
I'm planning to separate out the shell part into a separate module once stabilized. I just want to keep it in here while I develop so I can have faster iteration times. For now, it should be fine to depend on https://deno.land/x/dax@0.4.0/src/shell.ts -- as the API is unlikely to change too much. See the `parseArgs` and `spawn` exports.

Overall, I wanted different defaults than both dzx and zx—no CLI, no globals or global config, forced cross platform shell, and a slightly different API so that's why I started from scratch on this as it's a pretty small library.
